<a href="https://colab.research.google.com/github/rafabelokurows/desmatamento-amazonia/blob/main/Desmatamento_munic%C3%ADpio_BR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Campeões do desmatamento

Objetivo: desenvolver um web app ou dashboard simples com alguns indicadores sobre desmatamento e infrações ambientais no Brasil

## Fontes de dados
* INPE (Prodes)
* Ibama

## Indicadores

### Desmatamento
* Municípios de maior área (e área de Amazônia)
* Mapa BR com os top N municípios
* Municípios onde ocorreu maior perda de área de floresta (Amazônica)

### Infrações 
* TOP N municípios em infrações Ibama
* TOP N indivíduos/empresas
* Infrações por ano/mês
* Infrações Amazônia Legal (por município)

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
desmatamento = pd.read_csv('/content/gdrive/MyDrive/desmatamento.csv')
municipios = pd.read_csv('/content/gdrive/MyDrive/municipios.csv')

In [44]:
desmatamento.head()
municipios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_municipio               5570 non-null   int64
 1   id_municipio_6             5570 non-null   int64
 2   id_municipio_tse           5570 non-null   int64
 3   id_municipio_rf            5570 non-null   int64
 4   id_municipio_bcb           5534 non-null   float64
 5   nome                       5570 non-null   object
 6   capital_uf                 5570 non-null   int64
 7   id_comarca                 5570 non-null   int64
 8   id_regiao_saude            5570 non-null   int64
 9   nome_regiao_saude          5570 non-null   object
 10  id_regiao_imediata         5570 non-null   int64
 11  nome_regiao_imediata       5570 non-null   object
 12  id_regiao_intermediaria    5570 non-null   int64
 13  nome_regiao_intermediaria  5570 non-null   object
 14  id_microrregiao            5570 non-null   int64
 15  nome_microrregiao          5570 non-null   object
 16  id_mesorregiao             5570 non-null   int64
 17  nome_mesorregiao           5570 non-null   object
 18  ddd                        5570 non-null   int64
 19  id_uf                      5570 non-null   int64
 20  sigla_uf                   5570 non-null   object
 21  nome_uf                    5570 non-null   object
 22  nome_regiao                5570 non-null   object
dtypes: float64(1), int64(13), object(9)
memory usage: 1001.0+ KB

In [45]:
df=pd.merge(desmatamento,municipios,how='left').loc[:,["ano","id_municipio","nome","area","desmatado","incremento","floresta","nuvem","nao_observado","hidrografia","nao_floresta","nome_uf"]]
df['pctdesmatado'] = df.desmatado / df.floresta
df.head()
#df['incrementopct'] = df.pctdesmatado /

,ano,id_municipio,nome,area,desmatado,incremento,floresta,nuvem,nao_observado,hidrografia,nao_floresta,nome_uf,pctdesmatado
0,2000,1100015,Alta Floresta D'Oeste,7137,1761.1,NaN,3639.6,0.0,6.1,22.2,1708.0,Rondônia,0.483872
1,2001,1100015,Alta Floresta D'Oeste,7137,1834.2,73.1,3566.5,0.0,6.1,22.2,1708.0,Rondônia,0.514286
2,2002,1100015,Alta Floresta D'Oeste,7137,1948.9,114.7,3451.8,0.0,6.1,22.2,1708.0,Rondônia,0.564604
3,2003,1100015,Alta Floresta D'Oeste,7137,2014.9,66.0,3385.8,0.0,6.1,22.2,1708.0,Rondônia,0.595103
4,2004,1100015,Alta Floresta D'Oeste,7137,2092.0,77.1,3308.7,0.0,6.1,22.2,1708.0,Rondônia,0.632272

In [34]:
df.query("ano == 2021").sort_values('area',ascending=False).head(10)

,ano,id_municipio,nome,area,desmatado,incremento,floresta,nao_floresta,nome_uf,pctdesmatado
3497,2021,1500602,Altamira,159540,11313.9,777.5,136905.2,3760.6,Pará,0.082640
1803,2021,1300409,Barcelos,124163,224.6,1.4,95832.4,17060.1,Amazonas,0.002344
2771,2021,1303809,São Gabriel da Cachoeira,112476,1230.9,5.6,98828.8,489.7,Amazonas,0.012455
5147,2021,1505304,Oriximiná,107782,1629.2,17.3,92074.6,3636.6,Pará,0.017694
2881,2021,1304104,Tapauá,90962,451.2,55.8,86238.2,2161.1,Amazonas,0.005232
5939,2021,1507300,São Félix do Xingu,84253,20471.5,585.3,58980.0,3788.0,Pará,0.347092
1759,2021,1300201,Atalaia do Norte,80005,251.0,1.7,75675.8,16.5,Amazonas,0.003317
3475,2021,1500503,Almeirim,72964,1956.5,31.9,61714.4,2715.5,Pará,0.031702
2375,2021,1302306,Jutaí,71756,279.1,1.1,64999.0,97.6,Amazonas,0.004294
2397,2021,1302405,Lábrea,69672,6118.5,551.6,61310.6,1793.3,Amazonas,0.099795

In [35]:
df.query("ano == 2021").sort_values('desmatado',ascending=False).head(10)

,ano,id_municipio,nome,area,desmatado,incremento,floresta,nao_floresta,nome_uf,pctdesmatado
5939,2021,1507300,São Félix do Xingu,84253,20471.5,585.3,58980.0,3788.0,Pará,0.347092
373,2021,1100205,Porto Velho,34631,11706.3,631.1,21710.4,431.9,Rondônia,0.539202
3497,2021,1500602,Altamira,159540,11313.9,777.5,136905.2,3760.6,Pará,0.082640
4773,2021,1504208,Marabá,15161,8928.2,74.7,6110.6,36.2,Pará,1.461100
5257,2021,1505502,Paragominas,19465,8869.0,31.6,9293.0,7.1,Pará,0.954374
5081,2021,1505064,Novo Repartimento,15432,8616.0,192.9,5644.0,1.0,Pará,1.526577
14893,2021,5105101,Juara,22666,8272.2,75.3,12493.7,1600.6,Mato Grosso,0.662110
4223,2021,1502764,Cumaru do Norte,17105,7528.9,47.6,8140.1,1436.0,Pará,0.924915
5785,2021,1506708,Santana do Araguaia,11609,7353.5,26.8,3382.2,808.4,Pará,2.174177
5059,2021,1505031,Novo Progresso,38183,7274.2,421.0,27376.8,3457.3,Pará,0.265707

In [37]:
df.query("ano == 2021").sort_values('pctdesmatado',ascending=False).head(50)

,ano,id_municipio,nome,area,desmatado,incremento,floresta,nao_floresta,nome_uf,pctdesmatado
9569,2021,1720309,São Sebastião do Tocantins,287,135.6,0.0,0.0,132.9,Tocantins,inf
12363,2021,2108504,Pindaré-Mirim,275,202.4,0.0,0.0,52.8,Maranhão,inf
10339,2021,2101772,Bela Vista do Maranhão,147,127.0,0.0,0.0,20.8,Maranhão,inf
10493,2021,2102077,Bom Lugar,451,451.8,0.0,0.0,0.0,Maranhão,inf
10515,2021,2102150,Brejo de Areia,365,365.1,0.0,0.0,0.0,Maranhão,inf
13265,2021,2111706,São Vicente Ferrer,393,296.1,0.0,0.0,97.8,Maranhão,inf
13287,2021,2111722,Satubinha,447,356.2,0.0,0.0,86.7,Maranhão,inf
7259,2021,1703008,Babaçulândia,1796,3.5,0.0,0.0,1779.2,Tocantins,inf
13441,2021,2112274,Tufilândia,274,249.0,0.0,0.0,25.0,Maranhão,inf
12231,2021,2108108,Paulo Ramos,1063,1064.0,0.0,0.0,0.0,Maranhão,inf
16015,2021,5107297,São José do Povo,443,27.4,0.0,0.0,416.1,Mato Grosso,inf
13595,2021,2113009,Vitorino Freire,1209,1166.3,0.0,0.0,43.3,Maranhão,inf
10889,2021,2103554,Conceição do Lago-Açu,742,531.0,0.0,0.0,98.7,Maranhão,inf
12121,2021,2107407,Olho d'Água das Cunhãs,704,704.6,0.0,0.0,0.0,Maranhão,inf
11417,2021,2105203,Igarapé Grande,379,380.0,0.0,0.0,0.0,Maranhão,inf
11703,2021,2105948,Lago dos Rodrigues,196,196.8,0.0,0.0,0.0,Maranhão,inf
11637,2021,2105708,Lago da Pedra,1552,1552.1,0.0,0.0,0.0,Maranhão,inf
13243,2021,2111672,São Roberto,229,229.7,0.0,0.0,0.0,Maranhão,inf
11659,2021,2105807,Lago do Junco,312,312.4,0.0,0.0,0.0,Maranhão,inf
12759,2021,2109908,Santa Inês,778,766.3,0.0,0.0,8.6,Maranhão,inf
9943,2021,2100402,Altamira do Maranhão,542,542.5,0.0,0.0,0.0,Maranhão,inf
12407,2021,2108702,Pio XII,550,479.0,0.0,0.0,48.0,Maranhão,inf
11681,2021,2105906,Lago Verde,631,534.1,0.0,0.1,82.4,Maranhão,5341.000000
12143,2021,2107456,Olinda Nova do Maranhão,200,184.3,0.0,0.1,1.4,Maranhão,1843.000000
12561,2021,2109239,Presidente Médici,441,440.3,0.0,0.5,0.0,Maranhão,880.600000
11285,2021,2104651,Governador Newton Bello,1173,1166.1,0.0,3.6,0.0,Maranhão,323.916667
11901,2021,2106508,Matinha,414,291.0,0.1,1.3,49.2,Maranhão,223.846154
8007,2021,1708254,Fortaleza do Tabocão,624,402.6,0.0,1.8,219.6,Tocantins,223.666667
7545,2021,1703891,Carrasco Bonito,194,131.3,0.0,0.6,57.9,Tocantins,218.833333
7435,2021,1703800,Buriti do Tocantins,250,214.2,0.0,1.0,29.0,Tocantins,214.200000
12869,2021,2110500,São Bento,465,362.9,0.0,1.7,99.8,Maranhão,213.470588
7655,2021,1705508,Colinas do Tocantins,847,663.1,0.0,4.0,179.9,Tocantins,165.775000
11989,2021,2106805,Mirinzal,696,681.5,0.0,4.7,0.0,Maranhão,145.000000
14695,2021,5104203,Guiratinga,5359,168.3,0.0,1.7,5189.0,Mato Grosso,99.000000
12275,2021,2108256,Pedro do Rosário,1770,1681.9,0.4,18.2,69.4,Maranhão,92.412088
9261,2021,1718709,Rio dos Bois,848,17.8,0.0,0.2,828.1,Tocantins,89.000000
12803,2021,2110039,Santa Luzia do Paruá,908,865.4,0.0,10.4,30.5,Maranhão,83.211538
13221,2021,2111631,São Raimundo do Doca Bezerra,284,280.3,0.0,3.7,0.0,Maranhão,75.756757
9987,2021,2100477,Alto Alegre do Pindaré,1951,1866.3,0.0,27.2,53.5,Maranhão,68.613971
14827,2021,5104807,Jaciara,1657,687.1,0.0,11.2,958.7,Mato Grosso,61.348214
8645,2021,1714880,Nova Olinda,1573,799.1,0.0,14.9,759.0,Tocantins,53.630872
11615,2021,2105658,Junco do Maranhão,560,547.4,0.1,10.6,0.0,Maranhão,51.641509
16081,2021,5107404,São Pedro da Cipa,343,305.9,0.0,6.1,31.0,Mato Grosso,50.147541
7391,2021,1703602,Brasilândia do Tocantins,643,219.3,0.0,4.6,419.1,Tocantins,47.673913
12187,2021,2107605,Palmeirândia,532,440.8,0.0,9.7,58.0,Maranhão,45.443299
11395,2021,2105153,Igarapé do Meio,397,218.1,0.3,4.9,172.9,Maranhão,44.510204
7347,2021,1703206,Bernardo Sayão,930,895.3,0.0,20.6,0.0,Tocantins,43.461165
8953,2021,1716703,Colméia,995,756.3,0.4,17.9,220.8,Tocantins,42.251397
15949,2021,5107206,Rio Branco,529,446.2,0.0,10.6,72.2,Mato Grosso,42.094340
8491,2021,1713304,Miranorte,1036,319.1,0.0,8.4,708.5,Tocantins,37.988095

In [46]:
df['diffdesmatado'] = df.sort_values(['nome','nome_uf','ano']).groupby(['nome','nome_uf'])['desmatado'].diff(1)
df.groupby('ano').diffdesmatado.sum()
# df.query("ano == 2021").sort_values('diffdesmatado',ascending=False).head()
# df.query("nome == 'Candeias do Jamari'")

ano
2000        0.0
2001    54511.1
2002    25713.0
2003    30379.1
2004    27166.5
2005    23889.8
2006    10898.5
2007    11500.7
2008    13300.7
2009     6550.8
2010     6333.6
2011     5609.7
2012     4454.2
2013     5409.0
2014     5123.6
2015     6144.3
2016     7265.7
2017     3797.4
2018    10886.3
2019    11043.8
2020    10587.5
2021    12620.2
Name: diffdesmatado, dtype: float64

In [43]:
df.query("nome_uf == 'Tocantins' & ano==2021 & incremento > 0")
df.query("nome == 'Altamira'")

,ano,id_municipio,nome,area,desmatado,incremento,floresta,nuvem,nao_observado,hidrografia,nao_floresta,nome_uf,pctdesmatado
3476,2000,1500602,Altamira,159540,2058.8,NaN,152013.6,16.2,22.5,1668.3,3760.6,Pará,0.013544
3477,2001,1500602,Altamira,159540,2634.7,575.9,151453.9,0.0,22.5,1668.3,3760.6,Pará,0.017396
3478,2002,1500602,Altamira,159540,3309.0,674.4,150776.2,3.4,22.5,1668.3,3760.6,Pará,0.021946
3479,2003,1500602,Altamira,159540,3924.7,615.6,150163.9,0.0,22.5,1668.3,3760.6,Pará,0.026136
3480,2004,1500602,Altamira,159540,4602.7,678.0,149423.6,62.3,22.5,1668.3,3760.6,Pará,0.030803
3481,2005,1500602,Altamira,159540,5142.1,539.4,148685.6,260.9,22.5,1668.3,3760.6,Pará,0.034584
3482,2006,1500602,Altamira,159540,5428.6,286.5,144092.7,4567.3,22.5,1668.3,3760.6,Pará,0.037674
3483,2007,1500602,Altamira,159540,5797.8,369.2,147682.9,605.2,25.2,1668.3,3760.6,Pará,0.039258
3484,2008,1500602,Altamira,159540,6138.8,340.9,144968.9,2977.7,25.7,1668.3,3760.6,Pará,0.042346
3485,2009,1500602,Altamira,159540,6529.9,391.2,138843.4,8709.7,28.1,1668.3,3760.6,Pará,0.047031
3486,2010,1500602,Altamira,159540,6726.0,196.1,146913.3,446.6,25.2,1668.3,3760.6,Pará,0.045782
3487,2011,1500602,Altamira,159540,6964.3,238.3,145488.9,1632.3,25.6,1668.3,3760.6,Pará,0.047868
3488,2012,1500602,Altamira,159540,7194.2,229.8,145701.0,1189.9,26.0,1668.3,3760.6,Pará,0.049376
3489,2013,1500602,Altamira,159540,7490.1,296.0,138401.9,8176.7,42.4,1668.3,3760.6,Pará,0.054118
3490,2014,1500602,Altamira,159540,7784.1,293.9,142469.8,3834.7,22.5,1668.3,3760.6,Pará,0.054637
3491,2015,1500602,Altamira,159540,8092.6,308.6,142658.4,3360.1,0.0,1668.3,3760.6,Pará,0.056727
3492,2016,1500602,Altamira,159540,8502.1,409.5,143007.0,2602.0,0.0,1668.3,3760.6,Pará,0.059452
3493,2017,1500602,Altamira,159540,8727.0,224.9,145384.1,0.0,0.0,1668.3,3760.6,Pará,0.060027
3494,2018,1500602,Altamira,159540,9161.9,435.0,135599.9,9349.3,0.0,1668.3,3760.6,Pará,0.067566
3495,2019,1500602,Altamira,159540,9737.3,575.4,144373.8,0.0,0.0,1668.3,3760.6,Pará,0.067445
3496,2020,1500602,Altamira,159540,10536.4,799.1,143514.1,60.6,0.0,1668.3,3760.6,Pará,0.073417
3497,2021,1500602,Altamira,159540,11313.9,777.5,136905.2,5892.0,0.0,1668.3,3760.6,Pará,0.082640